networks:
  mynet:
    driver: bridge
    
services:
  container-dev:
    build:
      context: .
      dockerfile: Dockerfile.remote
    container_name: container_dev 
    networks: 
      - mynet
    volumes: 
      - ".:/app" 
    ports: 
      - "8082:8082" 
  app:
    build:
      context: ./src/api
      dockerfile: Dockerfile
    networks:
      - mynet
    ports: 
      - 8083:8080
  redis:
    image: redis
    command: redis-server --requirepass Rids2019!
    ports:
      - 6379:6379
    networks:
      - mynet